name: Test on macOS
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build Unstable"]
    branches: [master]
    types:
      - completed

jobs:
  test:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - name: Download Precompiled Companion App
      run: curl -L https://github.com/mrrfv/open-android-backup/releases/download/latest/app-release.apk -o open-android-backup-companion.apk
    - run: brew install p7zip pv bash dialog
    - run: chmod +x ./.github/test-script.sh

    - uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        script: 'bash ./.github/test-script.sh'
